### ISSUE TITLE
Use packagekit to be distribution independent

### ISSUE THREAD

**Issue by HeikoAdams** [RaphaelRochet/arch-update#1]
If this extension would (optionally) would use packagekit instead of packman it could be used for all distributions using packagekit too.

**Comment by HeikoAdams** [comment]
PackageKit has a "get-updates" command which fetches the list of available updates and a "update" command to apply updates. AFAIK both don't need root permissions.

**Comment by RaphaelRochet** [comment]
It would lead to name change and new icons but why not. I will look at it.

**Comment by RaphaelRochet** [comment]
I've had a look at packagekit and it's too bad that  "pkcon get-updates -p" command sends so much garbage on standard output ...

**Comment by HeikoAdams** [comment]
And what about the return codes? Isn't there a way to get and check them?

**Comment by RaphaelRochet** [comment]
Return codes can tell if a command ran without errors, or maybe if there are updates. But then it won't tell us how many, or what they are. I found a few JS libs but no really stable choice.

Note that the output of ```LC_ALL=C pkcon get-updates -p``` can be parsed. Only extra work ...

**Comment by RaphaelRochet** [comment]
Since commit c9ac6d9eb0080861f6117bba6c4691378ae94d0b it is now possible to use anything that will return 1 update per line as a check update command. One step forward to packagekit usage.
A tiny perl script could be written to wrap packagekit's get-updates.
