### ISSUE TITLE
Parameters changes are not stored

### ISSUE THREAD

**Issue by grm34** [RaphaelRochet/arch-update#100]
Hi and thanks for this useful extension.

I can't modify extension parameters, changing any of them result in blank line.

<a href="https://i.imgur.com/6z8ZiP1.png">
  <img src="https://i.imgur.com/6z8ZiP1.png">
</a>

**Comment by RaphaelRochet** [comment]
Hi,
What GNOME Shell version are you using ? Is there anything in the log ?

**Comment by grm34** [comment]
I'm using Gnome 3.28.0.
Nothing special in gnome-shell logs

**Comment by RaphaelRochet** [comment]
Unfortunately I can't reproduce this behavior :(

**Comment by grm34** [comment]
Fixed by downgrading [GNOME Shell integration](https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome) to stable ([chrome-gnome-shell](https://www.archlinux.org/packages/extra/any/chrome-gnome-shell/) instead of [chrome-gnome-shell-git](https://aur.archlinux.org/packages/chrome-gnome-shell-git/?comments=all)), reboot and re-install the extension.
