### ISSUE TITLE
Wiki update: aurman support

### ISSUE THREAD

**Issue by grm34** [RaphaelRochet/arch-update#101]
aurman works like a charm using:

## aurman
* Check command : ``/bin/sh -c "/usr/bin/checkupdates && /usr/bin/aurman -Qqu -a"``
* Update command : ``gnome-terminal -e 'sh -c  "aurman -Syu ; echo Done - Press enter to exit; read" '``
* Update command (with terminator) : ``terminator -e 'aurman -Syu ; echo Done - Press enter to exit; read '``

**Comment by RaphaelRochet** [comment]
Thanks, I have updated the wiki.

**Comment by grm34** [comment]
Sorry i fail in my previous post `-a` is not valid/required by aurman to update AUR packages, the right update cmd is: `/bin/sh -c "/usr/bin/checkupdates && /usr/bin/aurman -Qqu"`

**Comment by RaphaelRochet** [comment]
Okay, edited.
