### ISSUE TITLE
yaourt checkupdate : wiki suggestion enhancement

### ISSUE THREAD

**Issue by squalou** [RaphaelRochet/arch-update#108]
Hi,

I've read the wiki https://github.com/RaphaelRochet/arch-update/wiki 

I would like to suggest a slight change to your 'yaourt check update' command, in order to get the version numbers too.

Problem with yaourt -Qu -a is that every output will be prepended by 'aur/' so I use a 'cut' to remove 4 first char

`/bin/sh -c "(/usr/bin/checkupdates; /usr/bin/yaourt -Qu -a | cut -c 5-) | sort -u -t' ' -k1,1"`

And by the way thanks for your work !

**Comment by RaphaelRochet** [comment]
Hi,

Feel free to add that as an alternative in the wiki. It is open to changes.

Raphaël

**Comment by squalou** [comment]
Hi,
cool, didn't notice it was open.
Done !
