### ISSUE TITLE
Clearer indication that pacman-contrib is required

### ISSUE THREAD

**Issue by HarlemSquirrel** [RaphaelRochet/arch-update#109]
I noticed that recently updating pacman broke this extension. I finally saw on the extension's page that the `pacman-contrib` package is now required. 

It would be nice to have this somewhere in the dropdown or settings menu so users do not have to hunt for the solution.

**Comment by RaphaelRochet** [comment]
Yep, you're definitely right, and moreover it's easy to do. Will do this in a future version.

**Comment by RaphaelRochet** [comment]
Done, and sent to extensions.gnome.org :)
