### ISSUE TITLE
Abnormally large right margin 

### ISSUE THREAD

**Issue by memeplex** [RaphaelRochet/arch-update#116]
I originally reported https://github.com/Ste74/manjaro-update/issues/1 for the manjaro flavor but can confirm that it's happening with yours too.

**Comment by memeplex** [comment]
See also my comment there https://github.com/Ste74/manjaro-update/issues/1#issuecomment-396081368

**Comment by RaphaelRochet** [comment]
Hi, it should be fixed by 30df8d9e32c29dda126d43b9a26230b1d292c245.
