### ISSUE TITLE
QUESTION - How to search for updates with yay and for flatpaks?

### ISSUE THREAD

**Issue by ghost** [RaphaelRochet/arch-update#118]
In the Wiki there is a info how this extension can search for updates with YAY and with flatpaks - but how would the check and update command look like if I want to search for updates with yay and for flatpaks?

**Comment by alexheretic** [comment]
Add the flatpak bit on the end, just as the aurhelper ones add aur checks after checkupdates.
```sh
print-repo-updates; print-aur-updates; print-flatpak-updates
```
