### ISSUE TITLE
List of updates appears twice after "sudo pacman -Sy"

### ISSUE THREAD

**Issue by coxackie** [RaphaelRochet/arch-update#120]
If one runs sudo pacman -Sy (without updating), and then checks updates again at arch-update, the list of packages that need updating appears with double entries for each package. This is not a deal breaker, of course, but would be nice to fix.

**Comment by RaphaelRochet** [comment]
Do you use default config (checkupdates script) ? I do see duplicates in "checkupdates" output.

**Comment by coxackie** [comment]
I use the + yay version from your wiki, which contains checkupdates:
```
/bin/sh -c "/usr/bin/checkupdates && /usr/bin/yay -Qqu --color never | sed 's/Get .*//'"
```
In fact, the AUR packages never appear double.

**Comment by RaphaelRochet** [comment]
I guess "yay" is listing both pacman (system database) and aur updates.
You should consider adding a "sort -u" somewhere to dedupe updates.

Maybe like this : 
```
/bin/sh -c "(/usr/bin/checkupdates && /usr/bin/yay -Qqu --color never | sed 's/Get .*//') | sort -u -t' ' -k1,1"
```
Do not hesitate to update the wiki if you come to a better solution !

**Comment by coxackie** [comment]
You are right, indeed, there is something with `yay`. I am simply using for the time being
```
/bin/sh -c "/usr/bin/yay -Qqu --color never | sed 's/Get .*//'"
```
(without `checkupdates` invoked at all) and it seems to work ok. Do you think this is a simpler solution? I do not want to touch the wiki for the time being, if I am not sure that it is indeed consistent.

**Comment by RaphaelRochet** [comment]
You'll have to check when new updates will come. But I'm afraid yay won't update the main pacman database, and thus won't tell you about new updates (until you du a "pacman -Sy" of course).

**Comment by coxackie** [comment]
you are absolutely right. Your suggestions works just fine, maybe you can update the wiki (you have higher authority on this), and consider this issue closed. Many thanks!
