### ISSUE TITLE
Automatic downloads

### ISSUE THREAD

**Issue by tr0yspradling** [RaphaelRochet/arch-update#121]
Is there a setting to enable automatic downloads (not installing), for caching? This speeds up the update process a good bit for me.

**Comment by RaphaelRochet** [comment]
I think you can easily do that by running "pacman -Syuw --noconfirm" from root crontab or systemd timer.

**Comment by tr0yspradling** [comment]
Right. This seems to be a convenient feature in other managers, maybe consider implementing this?

**Comment by RaphaelRochet** [comment]
I don't know ... I see potential security issues there ... The extension does not (and shall not) have root access and can't do that without lowering the security (may it a suid script or changed rights).
One can change the update check script to download packages in a secondary location, that pacman would take into account somehow, ... but that become more complex than a simple cron.
