### ISSUE TITLE
Update = Nothing | Flatpak

### ISSUE THREAD

**Issue by Truemmerer** [RaphaelRochet/arch-update#124]
With Flatpak an update is displayed which is called "Nothing".
But there is no update.

**Comment by alexheretic** [comment]
Ok maybe there is a better way: https://github.com/flatpak/flatpak/issues/2168

```sh
flatpak remote-ls --columns=application -a --updates
```

**Comment by RaphaelRochet** [comment]
I saw you updated the wiki as well, thank you :+1:
