### ISSUE TITLE
Arch logo is invisible when using Gnome 3.32

### ISSUE THREAD

**Issue by Nik-mmzd** [RaphaelRochet/arch-update#127]
Updates count is visible

**Comment by jjgalvez** [comment]
the icon is not visible against the black top bar, need to make the icon white or some other color

**Comment by jjgalvez** [comment]
I take it back its not the color the icons are just not showing up at all, and its not emitting any errors

**Comment by RaphaelRochet** [comment]
I'll try to upgrade my box and check this tomorrow. Let's hope it'll be an easy fix.

**Comment by RaphaelRochet** [comment]
v30 should fix this now. (Already submitted to extensions.gnome.org, waiting for review)

**Comment by jjgalvez** [comment]
> v30 should fix this now. (Already submitted to extensions.gnome.org, waiting for review)

sorry v30 didn't fix it on my end, still no icon :(
