### ISSUE TITLE
V30 still does not show up with gnome-shell 3.32

### ISSUE THREAD

**Issue by jjgalvez** [RaphaelRochet/arch-update#128]
V30 still not showing icon with gnome-shell 3.32

**Comment by allexlima** [comment]
+1

**Comment by sorin-mihai** [comment]
You might want to check again downloading the zip from github and placing it's content in the right directory. Neither the AUR package (29-1) nor the extensions.gnome.org method (v28) where updated a few moments ago when i checked. I grabbed the zip just a couple of hours after it was released and for me it's been working fine since.

**Comment by jjgalvez** [comment]
I'll give that a try




Get Outlook for Android







On Sun, Mar 17, 2019 at 4:18 PM -0700, "Sorin-Mihai Vârgolici" <notifications@github.com> wrote:












You might want to check again downloading the zip from github and placing it's content in the right directory. Neither the AUR package (29-1) nor the extensions.gnome.org method (v28) where updated a few moments ago when i checked. I grabbed the zip just a couple of hours after it was released and for me it's been working fine since.

**Comment by RaphaelRochet** [comment]
Indeed the v30 is submitted on extensions.gnome.org but is still pending preview.
In the meanwhile you have to download and install the v30 zip manually :(

**Comment by jjgalvez** [comment]
Yep that worked great.




Get Outlook for Android







On Mon, Mar 18, 2019 at 1:23 AM -0700, "Raphaël Rochet" <notifications@github.com> wrote:












Indeed the v30 is submitted on extensions.gnome.org but is still pending preview.

In the meanwhile you have to download and install the v30 zip manually :(

**Comment by RaphaelRochet** [comment]
v30 is now live on extensions.gnome.org :+1:
