### ISSUE TITLE
Does not work with Gnome Version 3.32.0

### ISSUE THREAD

**Issue by maksim-ka** [RaphaelRochet/arch-update#130]
Does not show up in the top bar. Restart did not help.

**Comment by RaphaelRochet** [comment]
Are you sure you are using v30 ?

**Comment by maksim-ka** [comment]
v30? No, version 3.32.0. The most recent stable one.

**Comment by RaphaelRochet** [comment]
I mean arch-update extension version

**Comment by maksim-ka** [comment]
My fault - v30 works!
Is there a chance that the Manjaro Indicator can get the update too?

**Comment by RaphaelRochet** [comment]
Cool ;) Sorry I do not know about Manjaro !
