### ISSUE TITLE
Theme icons not used since update for GNOME 3.32

### ISSUE THREAD

**Issue by drakkar1969** [RaphaelRochet/arch-update#131]
One of the latest commits for GNOME 3.32 compatibility (https://github.com/RaphaelRochet/arch-update/commit/33b17571af7570f83e617175e3b5478e4fd99df0) means the indicator no longer uses system icon theme.
However some shell extensions that are working on GNOME 3.32 do have themeable icons on the indicator, e.g.:
- [OpenWeather](https://extensions.gnome.org/extension/750/openweather/)
- [Screenshot Tool](https://extensions.gnome.org/extension/1112/screenshot-tool/)

**Comment by RaphaelRochet** [comment]
Do you need themeable theme ? Do you know a theme that support arch-update ?
I may implement this.

**Comment by drakkar1969** [comment]
Papirus icon theme for example supports Arch update symbolic icons.
Not to say that this is a huge issue, just seems strange that this is no longer possible with the update. 
And to be fair, the default extension icons are actually very nice (on Arch, maybe less so if you're on another Arch based distro like Manjaro)

**Comment by RaphaelRochet** [comment]
Ok thanks, I did not know that !

**Comment by RaphaelRochet** [comment]
That is now working in v37 :)
