### ISSUE TITLE
GNOME 3.34 support, please

### ISSUE THREAD

**Issue by Kerrung** [RaphaelRochet/arch-update#133]
GNOME 3.34 support, please

**Comment by RaphaelRochet** [comment]
Hey, it works nice for me, do you an issue ?

**Comment by Kerrung** [comment]
But on a site with extensions for GNOME, I don't see 3.34 support.

**Comment by RaphaelRochet** [comment]
Ok, I see. I will update it quickly.

**Comment by RaphaelRochet** [comment]
That is now done. You can see 3.34 on https://extensions.gnome.org/extension/1010/archlinux-updates-indicator/ now.

**Comment by Kerrung** [comment]
> That is now done. You can see 3.34 on https://extensions.gnome.org/extension/1010/archlinux-updates-indicator/ now.

Thank you!
