### ISSUE TITLE
Can't see AUR updates if no updates in repositories

### ISSUE THREAD

**Issue by banditopazzo** [RaphaelRochet/arch-update#136]
Hi, I noticed this behaviour: if the `checkupdates` don't see any new packages, the AUR query will not be performed.
For example I use the following command to check updates:
```bash
/bin/sh -c "(/usr/bin/checkupdates && /usr/bin/yay -Qqu --color never | sed 's/Get .*//') | sort -u -t' ' -k1,1"
```
The problem I think is that `checkupdates` returns an exit code `1`  when it don't find updates and the `yay` command after `&&` will not be executed.
Maybe now the behaviour of `checkupdates` is different.

**Comment by RaphaelRochet** [comment]
Hey, you can try replacing ``&&`` by a semicolon ``;`` to remove that condition.

**Comment by banditopazzo** [comment]
Hi, yes it worked perfectly, thanks. I have updated the wiki.
