### ISSUE TITLE
Error: Too many open files

### ISSUE THREAD

**Issue by Strykar** [RaphaelRochet/arch-update#139]
![arch_upd_notif](https://user-images.githubusercontent.com/2946372/72141136-44d48980-33b8-11ea-8d63-066ac7c0ae85.png)

So recently, I've been getting this error, seems similar to https://github.com/RaphaelRochet/arch-update/issues/125

Restarting gnome-shell or the PC fixes it but it comes back shortly after.
How can I help troubleshoot this?

```
 strykar ~ ulimit -aH
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63917
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63917
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

 strykar ~ lsof | wc -l
304949
```

**Comment by RaphaelRochet** [comment]
This error is thrown by a component that is common to the shell and all extensions that use files.
My best guest would be looking for an extension that open lots of files, or open files often, and disabling it to see if the issue disappear.
I hope arch-update isn't guilty ... as I never had this error myself and I don't how arch-update, using one single temporary file descriptor every half hour could end up opening too many files.

**Comment by Strykar** [comment]
Thanks for the pointers, I'll test and report back.

**Comment by Strykar** [comment]
Not related to this extension, closing.
