### ISSUE TITLE
Advanced Setting: Define your own Update Program

### ISSUE THREAD

**Issue by mettke** [RaphaelRochet/arch-update#14]
It would be quite nice to be able to define your own Update Program like yaourt -Qqua

**Comment by RaphaelRochet** [comment]
"yaourt -Qqua" won't let you check **new** updates from repos : it needs a -Sy to sync databases, but then it will ask for password ... which is not possible (background process).
On then another hand, it may be a opening for #1 (be distribution independant) !

**Comment by RaphaelRochet** [comment]
If anyone can give real working use cases, maybe I will add this. 
A limited list of choices (checkupdates, yaourt, packagekit, ...) rather than a completely free command line may be safer.

**Comment by benneti** [comment]
"pacaur -Qu" could be used to include aur without password

**Comment by RaphaelRochet** [comment]
I don't know pacaur, is it able to check for updates for both official repositories and AUR without root access ?

**Comment by benneti** [comment]
yeah, "pacaur -Qu" does not need a passwort and "pacaur --help" says :
 "-S, -Q           extend pacman operations to the AUR"
Additionally i just tried it, and it shows all updates without root access

**Comment by benneti** [comment]
I would love to see pacaur integrated and would gladly help, but i dont have any real development skills, so is there another way?

**Comment by RaphaelRochet** [comment]
I've got issues with cower install from AUR and did not try pacaur, but a good solution to me is using "yaourt -Qqua" in addition to "checkupdates". Would it be an option for you ?

**Comment by benneti** [comment]
i would prefer cower/pacaur, since it should be more secure (as of my knowledge).
Did you add the needed key before installing (for me this was always the reason it failed).
At the moment i just changed the command to update the packages to use pacaur its good enough.
How could i add it, because i looked at the source and came to the conclusion that i propably can`t just replace "/..../checkupdates" with "pacaur -Qu".
By the way in my opinion this extension is the perfect way to keep my arch up to date.

**Comment by RaphaelRochet** [comment]
If pacaur can make an output similar to checkupdates you can simply change the command path/name in the source.

**Comment by benneti** [comment]
if i replace /usr/bin/checkupdates with pacaur -Qqu it will not work, do i need a skript or am i missing something? (pacaur -Qqu gives the updateable applications names one in every line, i think checkupdates does the same does it not?)

**Comment by RaphaelRochet** [comment]
You are right, the checkupdate gives one update per line. It pacaur does not, a wrapper is needed to parse its results and hand it back to arch update. That's a big part of our issue here (and the same in #1 )

**Comment by benneti** [comment]
![bildschirmfoto von 2015-12-13 20-05-00](https://cloud.githubusercontent.com/assets/11725645/11768715/34484a9e-a1d5-11e5-8039-0f341dab583f.png)
is this the right output format, because, i can't get it  to work with the extension?

**Comment by RaphaelRochet** [comment]
Ok so  pacaur does only list AUR updates ?
You cannot spawn a process with a command line like this. You have to run a shell, something like ;
```sh "checkupdates && pacaur -Qqu" ```

So in the source it may look like :
```
GLib.spawn_async_with_pipes(null, ['/usr/bin/sh','-c,'"/us/bin/checkupdates && pacaur -Qqu"'], null, Lib.SpawnFlags.DO_NOT_REAP_CHILD, null);
```
Not sure if double quotes are needed. You may need to use full path for pacaur.

**Comment by benneti** [comment]
thank you very much, i did not know this. i will try it and report back.
And thank you again for the awesome help you provide!

**Comment by benneti** [comment]
no this does not work either, i think there is a problem with the spaces. Can you point me to the resources to understand the used methods?
(I did add a ' and tried it with full path and without and some other changes, too)

**Comment by benneti** [comment]
This does not work either, i think there is a problem with the spaces. Can you point me to the resources to understand the used methods?
(I did add a ' and tried it with and  without full path and some other changes, too)
I found a workaround, but i think this is not the best way:
I created a bash script:
```
#!/bin/sh
# Skript to check repositories and aur for updates without root privileges
/usr/bin/checkupdates && /usr/bin/pacaur -Qqu -a
```
did a "chmod -x path_to_skript" and then replaced "/usr/bin/checkupdates" with "full_path_to_skript".
Now i get notified about all updates.

**Comment by benneti** [comment]
and sorry, i forgot to answer your question:
yes it only lists aur updates and with "-a" I'm sure it does not even try to check for updates in the repositories

**Comment by RaphaelRochet** [comment]
Details on ```spawn_async_with_pipes``` :
https://people.gnome.org/~gcampagna/docs/GLib-2.0/GLib.spawn_async_with_pipes.html

What update command do you use now ? ```pacaur -Syyua``` ?

**Comment by benneti** [comment]
I use "pacaur -Syu"  wich basically is the same as "pacman -Syu" with aur support.
And thank you again.

**Comment by RaphaelRochet** [comment]
Now it is possible ;) Added in c9ac6d9eb0080861f6117bba6c4691378ae94d0b. Will be included in next release.

**Comment by frank604** [comment]
Great extension.  So to clarify, in 'Advance Settings' we can change command to check for package updates from /usr/bin/checkupdates to path/to/file/updatescript which has`#!/bin/sh
# Skript to check repositories and aur for updates without root privileges
/usr/bin/checkupdates && /usr/bin/pacaur -Qqu -a`
And it will then use pacaur to pull in package updates from official repo and aur?  Assuming we use pacaur.

**Comment by RaphaelRochet** [comment]
Yes. You can also call a shell like we do for update. It's trickier but does not require to create an additional script file.
eg:
```/bin/sh -c "/usr/bin/checkupdates && /usr/bin/pacaur -Qqu -a"```

**Comment by frank604** [comment]
That is even better.  Thank you for the update.
