### ISSUE TITLE
[Feature request] Check remote Arch installs for updates

### ISSUE THREAD

**Issue by Strykar** [RaphaelRochet/arch-update#140]
Use case: I run arch as my daily driver desktop and also on some remote VMs and SBCs and getting to see their update status without opening a terminal and through an extension and I have and love would be great :)

Is this something you would consider, SSH would be an obvious choice auth and transport?

**Comment by RaphaelRochet** [comment]
You could make scripts for arch-update to to that.
Status in arch-update come from a command you can change : nothing prevents you from creating a bash script that will fetch info from multiple hosts and use is as a "check for updates command" , and likewise create a script that will update multiples hosts as a "update packages" command !
Arch-update is expecting packages names from the "check for updates" script but it could also be something else, like the hostnames of hosts not up-to-date (Local host could be one of them) !

**Comment by Strykar** [comment]
Fair enough, could we add an option for a 3rd/4th command for remote machines then? I use the first two for pacman and aur updates.

**Comment by RaphaelRochet** [comment]
At this point, I think it's best to add a full custom commands feature (Adding as many as menu entries as one need) than adding things like "Custom command 1", "Custom command 2" and so on.
Or going further and adding a full "Remote check" support, with "check command" and "update command" fields for each remote host ... 
I don't know how much all this could be useful though. I try to follow KISS principle and "Custom launcher" or "Remote supervision" is a bit off-topic.
Not closed, may wait for more people asking for it.
