### ISSUE TITLE
[Feature request] Hide options button from panel

### ISSUE THREAD

**Issue by ghabit** [RaphaelRochet/arch-update#143]
GNOME now have an extensions dedicated app, 
also GNOME is simple to USE de without bloated KDE-like UI tools,
so maybe it will be right decision to remove 'options' button from menu at gnome-panel?

**Comment by RaphaelRochet** [comment]
Hi, thanks for you feed back.

My answer will be a clear "No". Let me explain why.

In fact this is not new, you can trigger extension options dialog from the https://extensions.gnome.org/local/ page or even from gnome-tweaks for a long time now.
This has never made me feel I should remove the "Options" from the indicator drop-down. I personally like to have direct access to it.

Also, gnome-extensions is optional and may not be available. (I had to manually install it)

I **may** change my mind later, only if gnome-extensions become part of gnome-control-center :smiley:
