### ISSUE TITLE
Spelling mistake "packager manager" instead of "package manager"

### ISSUE THREAD

**Issue by BlueBeetle97** [RaphaelRochet/arch-update#144]
I know it is a minor mistake. 
It is properly spelled in the settings.
![image](https://user-images.githubusercontent.com/23264270/77827192-299e2e00-710c-11ea-9f77-3a365d973fd0.png)
![image](https://user-images.githubusercontent.com/23264270/77827206-37ec4a00-710c-11ea-85f3-b57fbc47d6e1.png)

**Comment by RaphaelRochet** [comment]
Damned. How come nobody saw this !
Thanks I'll fix this.

**Comment by RaphaelRochet** [comment]
This is fixed in master. Will be in next release :)
