### ISSUE TITLE
Settings is broken in Gnome 3.36

### ISSUE THREAD

**Issue by memeplex** [RaphaelRochet/arch-update#146]
When I press the settings entry in the context menu nothing happens.

Opening settings from Tweaks or from the Extension App works fine.

**Comment by memeplex** [comment]
Please see https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/pull/203 for a possible solution.

**Comment by RaphaelRochet** [comment]
Thanks, I'll fix this asap

**Comment by RaphaelRochet** [comment]
Awesome. In 3.36.1 you can't use the old way, neither the new easy way.
NM, I used the hard way !
Fixed in 906e7bf02f493fe9e651680a4b1224809cc0a607

**Comment by memeplex** [comment]
Thanks! Is it supposed to be already available from gnome extensions website?

**Comment by memeplex** [comment]
Ah, no, I see it's v36 while only versions up to v35 are listed at their website, no hurries just wanted to check if I was testing the right version.

**Comment by RaphaelRochet** [comment]
I have submitted it yes, but it's waiting for review.
