### ISSUE TITLE
[Feature request] Display the latest in Arch News if there's new news before updating

### ISSUE THREAD

**Issue by ksdrummer** [RaphaelRochet/arch-update#147]
It would be so great to be able to know when there is an arch news. I'm wondering if this is easily doable or not. What do you think ?

For now I'm using 'yay -Pw'. I don't think pacman can do it...

**Comment by RaphaelRochet** [comment]
You can simply change the update commande to do that.
On https://github.com/RaphaelRochet/arch-update/wiki you can find this example with yay :
```
gnome-terminal -e 'sh -c "yay ; echo Done - Press enter to exit; read" '
```
You could change it to your liking; ie run `yay -Pw` before the upgrade :
```
gnome-terminal -e 'sh -c "yay -Pw ; yay ; echo Done - Press enter to exit; read" '
```

**Comment by ksdrummer** [comment]
Yes that's what I'm using and it does the job !
However, having a separated notification for the arch news only would be even better in my humble opinion.
I may not be looking at the good place though, I just want a notification on my gnome desktop everytime there is an arch news. If I had that, I wouldn't need anything else.

Thank you for your quick answer and the great job on the app ;)

**Comment by RaphaelRochet** [comment]
I see. I think this would go too far from arch-update core.
Another user asked about arch security news some time ago ( #77 ).
Maybe there's something to do with all that in a extension dedicated to arch-security-news ....

**Comment by ksdrummer** [comment]
I don't know for the arch-security-news. The arch news are important for all arch users.
But you're right it could be handled by another extension. I would love to have an extension just for displaying the arch news and nothing more. I'm not a developer but it seems an interesting mission and I'll give it a thought ;)
Thank you again for your answer !
