### ISSUE TITLE
Italian translation missing

### ISSUE THREAD

**Issue by Razer0123** [RaphaelRochet/arch-update#149]
Hello love the app, just one minor issue. When there are updates, i still get "updates pending" instead of the italian translation that should be something like "Aggiornamenti in attesa", could you fix this?

Best regards

**Comment by RaphaelRochet** [comment]
Hi,

Does this sounds correct for you ? (This is what should de displayed)
```
msgid "%d update pending"
msgid_plural "%d updates pending"
msgstr[0] "1 aggiornamento disponibile"
msgstr[1] "%d aggiornamenti disponibili"
```
Which version do you use ? (It's visible in settings, on top right)

**Comment by Razer0123** [comment]
Hello Raphael, i have v36, gnome extensions did not notify me an update yet

Pending has a different meaning that available, but i suppose that should not be an issue :)

Thank you for your prompt reply

**Comment by RaphaelRochet** [comment]
v37 is live on https://extensions.gnome.org/extension/1010/archlinux-updates-indicator/ (it has been approved a few days ago).
Can you try it ?

**Comment by Razer0123** [comment]
The website would not install latest version, i had to do it manually

Unfortunately ATM i don't have any package to update, i will report soon enough

PS: i know the new icon makes more sense, but i liked the arch logo way better.
PPS: Is it possible to reduce the new icon spacing? Takes a lot of empty space on both sides

**Comment by RaphaelRochet** [comment]
In settings you have "Use built--in icons" to force Arch icons I provide with the extension.

**Comment by Razer0123** [comment]
Translation seems to be fixed in v37, sorry to have wasted your time, i still have no idea why gnome.extensions won't update this one

**Comment by RaphaelRochet** [comment]
You're welcome.
Maybe you are using GNOME Shell 3.36 or older ?
The extension targets 3.36.1 or later, due to some API changes

**Comment by Razer0123** [comment]
Unlikely, i am running 3.36.3
