### ISSUE TITLE
Error message if checkcommand fails

### ISSUE THREAD

**Issue by agaengel** [RaphaelRochet/arch-update#150]
If the check command fails there is no message that this happend

e.g. if pacman-contrib is not installed the checkupdates is not present, but there is no message that it failed.

I would also suggest to add some hint that the package should be installed.

Regards
Alex

**Comment by RaphaelRochet** [comment]
There should be one, i.e : (it's in french here, says "Warning : you must install pacman-contrib to use checkupdates script")
![image](https://user-images.githubusercontent.com/1675389/85982951-f27b3980-b9e6-11ea-9be6-b81bf2f10c73.png)

I simply changed the 'Check command' to something non existing to obtain this message.

Did you modify Check command ?
