### ISSUE TITLE
Updating indicator after empty update

### ISSUE THREAD

**Issue by TheJackiMonster** [RaphaelRochet/arch-update#153]
I have many times the case that the indicator shows me an amount of packages which tend to have updates but if I update them via pacman directly from terminal, the indicator won't change. Even if I hit "Check now" or "Update now" and it responses with "There are no package updates available for your computer at this time", it still keeps the old list of updates to indicate.

So I would propose that an update call actually clears the indicator afterwards if no packages to update could be found or that checking for updates replaces the old list of patches to indicate.

**Comment by RaphaelRochet** [comment]
Whatever you set in "Command to check for package updates" setting seems to have trouble updating status.
Are you using the default ?
It's `/usr/bin/checkupdates` , which requires package pacman-contrib.

**Comment by TheJackiMonster** [comment]
Yes, I use the default.

**Comment by RaphaelRochet** [comment]
Is the indicator itself showing «updates available» status ? Or is it only the actual list in the menu that is not up-to-date ?
What does `checkupdates` show when this happens ?

**Comment by TheJackiMonster** [comment]
The indicator shows that updates are available and I can click on "Update now" but it closes with "There are no package updates available for your computer at this time".

I will try using checkupdates from terminal if it happens again and post it.

**Comment by TheJackiMonster** [comment]
Can't reproduce... The last three times I installed updates, the extension checked for changes afterwards and reset the indicator as to expect. I'm not sure if it is fixed somehow or not but I would close the issue, I think.
