### ISSUE TITLE
Feature Request: Don't count all lines in package updates check command output

### ISSUE THREAD

**Issue by ckotte** [RaphaelRochet/arch-update#155]
Would it be possible to exclude lines starting with "---" or something else from counting?

I use a custom script that checks pacman and AUR updates:
```
checkupdates
pikaur -Qua 2>/dev/null | awk '{$1=$1};1'
```

I would like to use an additional line to better separate pacman from AUR packages or even create a heading like ```pacman:``` and ```AUR:```  , but they will count as updates pending.

Example without any additional lines:
![image](https://user-images.githubusercontent.com/8488565/99118067-20a89100-25f7-11eb-84fb-aa1d403b1c4a.png)

Example with additional line:
![image](https://user-images.githubusercontent.com/8488565/99118013-0ec6ee00-25f7-11eb-9b93-825ecb6d8738.png)

**Comment by RaphaelRochet** [comment]
I am thinking of actually parsing the output to have a better display with versions aligned.
I'd then only count correct entries and thus let you add separator or headers as you like.

**Comment by ckotte** [comment]
@RaphaelRochet Sounds great!

**Comment by ckotte** [comment]
@RaphaelRochet Any news on this?

**Comment by RaphaelRochet** [comment]
It's still in to-do ... but this reminder is welcome. I still want to make that list a bit more readable.

**Comment by RaphaelRochet** [comment]
Good news ... I suggest you try out the latest commit ;)
![image](https://user-images.githubusercontent.com/1675389/182122171-2f7e4f5e-8f65-42f7-89ff-420c8b67da1b.png)

**Comment by ckotte** [comment]
It works! Thank you very much.

**Comment by ckotte** [comment]
It works! Thank you very much.
