### ISSUE TITLE
When there are a lot of updates, the list of packages is partially hidden

### ISSUE THREAD

**Issue by zegkljan** [RaphaelRochet/arch-update#156]
As the title says, when there are a lot of updates (I don't have the lower limit but I remember it mostly when there is 100-200 updates), the list of upgradable packages, when scrolled, is partially hidden. The part that is visible when no scrolling has been done yet is always completely visible, it dissapears in the area that needs to be scrolled to. See the enclosed screenshot.

My arch-update settings:
Version: Arch-update v38
Time to wait before first check: 15
Interval between updates check: 60
Strip out version numbers: on (although has no effect)
Always visible: on
Use build-in icons: off
Show updates count on indicator: on
Auto-expand updates list if updates count is less than this: 20
Position in Panel: right, 0
Send a notification when new updates are available: off
Use transient notifications: on
How much information to show on notifications: Count only
Command to check for package updates: `/bin/sh -c "(/usr/bin/checkupdates && /usr/bin/yay -Qqu --color never | sed 's/Get .*//') | sort -u -t' ' -k1,1"`
Command to update packages: `gnome-terminal -e 'sh -c "yay ; echo Done - Press enter to exit; read" '`
Pacman local directory path: `/var/lib/pacman/local`
Command to open package manager: empty

GNOME Shell version: 3.38.1
Windowing system: X11 (version 1.20.9.r21.g5c400cae1-2)

![Screenshot from 2020-11-26 15-50-00](https://user-images.githubusercontent.com/6035604/100365311-9a7d4900-2fff-11eb-97d3-73d1506b07d2.png)

**Comment by RaphaelRochet** [comment]
That's a lot of updates ;)
I'll see if I can reproduce it.

**Comment by RaphaelRochet** [comment]
Should be fixed in latest commit in master ;)

**Comment by zegkljan** [comment]
I can confirm the fix works. Thanks!
