### ISSUE TITLE
Question, Packages required to modify the extension

### ISSUE THREAD

**Issue by jlimas** [RaphaelRochet/arch-update#159]
Hello, this might not really be an issue with the app, just wondering if you could point me in right direction regarding the libraries I need to install to modify this extension.

I'm getting the following error message. I'm running Arch Linux. Thanks for any advise!

```
(gjs:6896): Gjs-CRITICAL **: 09:05:31.561: JS ERROR: Error: Requiring St, version none: Typelib file for namespace 'St' (any version) not found
@extension.js:23:25

(gjs:6896): Gjs-CRITICAL **: 09:05:31.561: Script extension.js threw an exception
```

**Comment by RaphaelRochet** [comment]
Hi,
the file "extension.js" is meant to be loaded by GNOME Shell, I don't think you can run it directly. 
I use the good old gedit to edit the file myself.
Sorry
