### ISSUE TITLE
Extension icon is gone?!

### ISSUE THREAD

**Issue by stnert** [RaphaelRochet/arch-update#162]
I tried every which way to reactivate it, and the extension icon is gone... what happened?

**Comment by RaphaelRochet** [comment]
Is the extension running ?
Can you access settings from gnome tweaks / extensions or [here on ego](https://extensions.gnome.org/extension/1010/archlinux-updates-indicator/) ?
If 'Error' after upgrade, simply restart GNOME Shell.
Check in settings if you have "Always visible" checked, and also "Use build-in icons" in case there's an issue with  your icon theme.
