### ISSUE TITLE
Custom command on cancelling checking updates

### ISSUE THREAD

**Issue by moshiur-raj** [RaphaelRochet/arch-update#163]
I have modified my sudoers file such that `sudo pacman -Sy` can be done without needing a password. I am currently using pacman to check for updates. The problem occurs when arch-update tries to cancel checking updates. I think it is killing the pacman process and that does not delete the db.lck file so I have to manually delete it each time. Adding an option for enabling custom script for the cancel button will really help a lot since I can just send a SIGINT signal to the pacman process and this does not leave the database locked.

**Comment by RaphaelRochet** [comment]
The cancel action is using kill indeed, it sens a TERM signal.
I am not willing to add another custom command for this, but you can work around this I think.

You can write a small wrapper that can trap the TERM signal and to whatever needs to be done.

Here something I tried :

**wait.sh** (the 'pacman' process)
```bash
#/bin/bash
echo Sleeping
sleep 200
echo Woke up
```

**test.sh** (the wrapper)
```bash
echo I am $$ and going to sleep
touch /tmp/testterm.txt
trap "echo 'ouch'; rm /tmp/testterm.txt ; kill -INT -$$ ; exit" TERM
# The long process has to be run in background for the trap to be executed asynchronously
./wait.sh &
# Using 'wait' to wait until done
wait
```

**Comment by moshiur-raj** [comment]
I'll look into your solution.
Would using SIGINT by default instead of SIGTERM cause any problems for the extension?
If not can you implement it?

**Comment by RaphaelRochet** [comment]
Remember that one can change the check update command.
Changing that behavior may affect things other users may have made if they expect TERM.

If you had a look on the default command, `/usr/bin/checkupdates`, it shows you how easy it is to clean db.lck from a script wrapper :
```bash
trap 'rm -f $CHECKUPDATES_DB/db.lck' INT TERM EXIT
```

Also checking for updates can be still done with checkupdates I think. You can also change to `/usr/bin/checkupdates -d` to download any new package (given sudo is set up).

**Comment by moshiur-raj** [comment]
Thanks for the explanation. I switched to checkupdates, it seems much cleaner. I'll close the issue now.
