### ISSUE TITLE
Request [ Fedora support ]

### ISSUE THREAD

**Issue by MuhammedTaha02** [RaphaelRochet/arch-update#167]
Hello. This plugin is very nice. I use it often on Archlinux. But I could not find the fedora version of this plugin. I use the plugin in fedora in different ways. But it doesn't work as well as in archlinux.

**Comment by RaphaelRochet** [comment]
Is Fedora still on GNOME 3.x ? If so, maybe have a look at https://github.com/ironsigma/fedora-update . Looks like it's the most recent fork.
If GNOME 40.x, then ... maybe try to open an issue there ?

**Comment by MuhammedTaha02** [comment]
Fedora switched to gnome 40. I looked at the link you posted. But the project looks discontinued.

**Comment by RaphaelRochet** [comment]
Too bad.
I guess you could use arch-update and change commands if fedora packet manager can output something similar.
Maybe also use icons from fedora-update also ...
I can"t do much, I don't use Fedora.

**Comment by RaphaelRochet** [comment]
You can see workaround here : https://github.com/RaphaelRochet/arch-update/issues/169#issuecomment-847066864

**Comment by MuhammedTaha02** [comment]
> You can see workaround here : [#169 (comment)](https://github.com/RaphaelRochet/arch-update/issues/169#issuecomment-847066864)

Thanks :)

**Comment by purejava** [comment]
And you can check out:

[![ego](https://raw.githubusercontent.com/purejava/fedora-update/main/ego.svg)](https://extensions.gnome.org/extension/6406/fedora-linux-update-indicator/)

It’s a fork if this extension for Fedora.
