### ISSUE TITLE
Bug (Extension not work)

### ISSUE THREAD

**Issue by MuhammedTaha02** [RaphaelRochet/arch-update#168]
![image](https://user-images.githubusercontent.com/62564400/118086043-06941380-b3cc-11eb-82af-411f9e756045.png)

OS: Archlinux
Kernel: 5.10.36-1-lts

Edit: Journalctl
![image](https://user-images.githubusercontent.com/62564400/118086233-4bb84580-b3cc-11eb-9451-dfda2d9be237.png)

**Comment by RaphaelRochet** [comment]
Hi,
Did you just install the extension ? Does the bug persist after a Shell restart ?

**Comment by MuhammedTaha02** [comment]
Yes. I deleted the plugin and installed it over and over again. And I rebooted 3 times

**Comment by RaphaelRochet** [comment]
Do you have pacman-contrib installed ? (or changed the command not to use checkupdates)

**Comment by MuhammedTaha02** [comment]
> Do you have pacman-contrib installed ? (or changed the command not to use checkupdates)

Yes. The package you said is installed. And I didn't make any changes to the command.

![image](https://user-images.githubusercontent.com/62564400/118134541-b5574480-b40a-11eb-9132-674822db0214.png)

**Comment by RaphaelRochet** [comment]
Please try to run `/usr/bin/checkupdates`

**Comment by MuhammedTaha02** [comment]
> Please try to run `/usr/bin/checkupdates`

![image](https://user-images.githubusercontent.com/62564400/118135206-69f16600-b40b-11eb-813c-eabb376065a0.png)

**Comment by RaphaelRochet** [comment]
That sure is weird. The only reason lastUnknowErrorString is used is when an error is caught while checking updates.
You don't see any relevant error from gnome-shell or gjs just before the extension goes into error state ?

We can try to silence the error (it's maybe harmless), can you try to add this line 
```javascript
if (!this.lastUnknowErrorString) {this.lastUnknowErrorString = _('Unknown error')}
```

After these 2 lines (366 & 367) in `extension.js`
```javascript
// Error
this.updateIcon.set_gicon( this._getCustIcon('arch-error-symbolic') );
```

**Comment by MuhammedTaha02** [comment]
Yeah, problem is solved. Thanks :)

![image](https://user-images.githubusercontent.com/62564400/118137755-3c59ec00-b40e-11eb-9922-a252c5444c72.png)

**Comment by RaphaelRochet** [comment]
So weird. Well. We'll see if problem comes again in next release.

**Comment by saikat0511** [comment]
I encountered the same error today. strange because it has been working fine since months. 
extension menu says `you have to install pacman-contrib to use 'checkupdates' script` but it is already installed and working.

shell restart doesn't have any effect and attempting to toggle the extension results in the same error in the OP

**Comment by RaphaelRochet** [comment]
When you run the "check command" in a terminal, it works fine ?
