### ISSUE TITLE
/usr/bin/checkupdates: File or directory not found

### ISSUE THREAD

**Issue by Razer0123** [RaphaelRochet/arch-update#170]
Just reinstalled Arch and i am getting this error, do i need to install any dependency? Pacman is installed of course

**Comment by Razer0123** [comment]
Seems likle pacman-contrib is required, can you add to the readme file?

**Comment by RaphaelRochet** [comment]
May be a bug in the code, the extension should have show a message telling you that pacman-contrib is required. ( Added it in 2018 when checkupdates was removed from pacman package : #109  )

It's in the metadata and on the extensions.gnome.org description but true I should have added it to the readme too.

**Comment by RaphaelRochet** [comment]
Where did you see the error ?
I tried to remove pacman-contrib and the extension correctly told me to install it.
![image](https://user-images.githubusercontent.com/1675389/120148304-4c344700-c1e8-11eb-9af1-21c402f06a41.png)

**Comment by RaphaelRochet** [comment]
Done in 100256f979ca61fd31d4206c03a8b644021ab22d ;)

**Comment by Razer0123** [comment]
Came here to help you but seems like you did it all

I'll try to test once the extensions reaches the Gnome website

Thanks for your work

**Comment by RaphaelRochet** [comment]
The extension is on the Gnome Website for a long time now : here https://extensions.gnome.org/extension/1010/archlinux-updates-indicator/
