### ISSUE TITLE
Terminal is closing without user input

### ISSUE THREAD

**Issue by AdisonCavani** [RaphaelRochet/arch-update#176]
When I click ``Update now`` the gnome terminal pops for a 1/4 of second, and automatically closes.

My command to update packages:
```
gnome-terminal -e 'sh -c  \"sudo pacman -Syu ; echo Done - Press enter to exit; read _\" '
```

I've installed ``pacman-contrib``. Packages are not updating.

**Comment by RaphaelRochet** [comment]
Hi,

Looks like you command line has errors. 
I think it may be because of  the `\`, try removing them.

```
gnome-terminal -e 'sh -c "sudo pacman -Syu ; echo Done - Press enter to exit; read" '
```

**Comment by AdisonCavani** [comment]
That solves the problem. Thank you
