### ISSUE TITLE
Do not hide the indicator if an error occured

### ISSUE THREAD

**Issue by egormanga** [RaphaelRochet/arch-update#178]
Today I figured out why the indicator does not appear sometimes. Turns out that the `checkupdates` command fails, and it counts as ‘no updates’. Then I switched the indicator to be always there, and it was saying that there was an error.

So, — which also good for debugging purposes — an error should trigger the icon appearing too.

**Comment by RaphaelRochet** [comment]
You're right. Will fix this.
