### ISSUE TITLE
Advanced settings gone

### ISSUE THREAD

**Issue by ryaneford** [RaphaelRochet/arch-update#182]
can i get the default advanced settings?

**Comment by RaphaelRochet** [comment]
Hi,

Default check and update commands are on the wiki :
https://github.com/RaphaelRochet/arch-update/wiki

Default for pacman folder is `/var/lib/pacman/local`

**Comment by ryaneford** [comment]
> Hi,
> 
> Default check and update commands are on the wiki : https://github.com/RaphaelRochet/arch-update/wiki
> 
> Default for pacman folder is `/var/lib/pacman/local`

Thank you so much!
