### ISSUE TITLE
Better update launch command

### ISSUE THREAD

**Issue by Agvantibo** [RaphaelRochet/arch-update#184]
The default command to update packages currently is something like: 
`gnome-terminal -e  'sh -c "pacman -Syu ; echo Done - Press enter to exit; read"'`.
This has two minor problems:

1. The window's title is "terminal" which could be very confusing if you have one open already.
2. The default terminal size is oftentimes too small for `pacman` (and by extension, `yay`) to correctly display the table package list.
3. The `-e` option is deprecated and as such, shouldn't be relied on. See [gnome-terminal output here](https://termbin.com/14vp)

Therefore I suggest to change the default to a more efficient:
`gnome-terminal --window --geometry 132x24 -t "Arch Linux Update" --  sh -c  'pacman -Syu ; echo Done - Press enter to exit; read'`
Which solves all of the above.

**Comment by RaphaelRochet** [comment]
Default values are meant to "just work" for most users.

Thus, thanks you for the notice about "-e" being deprecated. I didn't know and it is indeed a good idea to replace it with "--". Will change it ASAP.

For the default window geometry, I don't think that enforcing size in the default command line is a good idea. It can have unwanted effects ie for someone with a small screen and a big font size.
But you are welcome to mention it in the wiki, it may help some users.

For the title, well ... That make the line less readable, and does not provide much. The terminal windows should be focused when opened, makes it easy to find it ...
But there again, why not mentioning in the wiki. I know Arch users sometimes love fancy little things like that ;)

**Comment by RaphaelRochet** [comment]
Done, thanks.
