### ISSUE TITLE
Add suport for yay and paru

### ISSUE THREAD

**Issue by crismblog** [RaphaelRochet/arch-update#185]
It would be nice to add support for yay and paru.

**Comment by FhilipeCrash** [comment]
technically it is supported, i use yay and i created a script to check for aur updates and in the extension advanced settings i put the path to the script. the script is just that
```
#!/bin/sh
checkupdates && /usr/bin/yay -Qum
```

and as you can see the extension shows aur updates are available, in this case it's vscode and flat remix

![image](https://user-images.githubusercontent.com/36455575/161395556-c9157d2e-ba01-4be9-9731-5425c4de3ee7.png)

I've never used paru but I believe it's possible to create a script for it too

**Comment by RaphaelRochet** [comment]
Hi,

Look in the wiki ; https://github.com/RaphaelRochet/arch-update/wiki

There are examples for both Paru and Yay.
