### ISSUE TITLE
Inconsistent icon theme

### ISSUE THREAD

**Issue by arthurflor23** [RaphaelRochet/arch-update#186]
Hi,
I'm using Papirus icon pack and the extension's icon apparently doesn't change on its first use:
![Screenshot from 2022-04-02 08-52-55](https://user-images.githubusercontent.com/11759042/161382200-d082cbd8-0e9f-4f4d-9ef9-31e96ea30d95.png)

After that, back to the normal
![Screenshot from 2022-04-02 08-55-23](https://user-images.githubusercontent.com/11759042/161382204-e95b6e50-8a74-40ea-9f9b-e4332bf74de7.png)

so, after updating
![Screenshot from 2022-04-02 08-55-50](https://user-images.githubusercontent.com/11759042/161382211-7175a57b-d9a7-49eb-aabf-5c7764c87189.png)

and finally, manual update
![image](https://user-images.githubusercontent.com/11759042/161382456-f0bf03f5-1502-49ee-875a-fe0fd103ffb4.png)

**Comment by RaphaelRochet** [comment]
I noticed that sometimes the API isn't reliable. I will try with your icon pack when I have some times, maybe I can find something ...
