### ISSUE TITLE
I hope to add kgx command support for gnome-console!

### ISSUE THREAD

**Issue by gqcdm** [RaphaelRochet/arch-update#187]
![image](https://user-images.githubusercontent.com/78142321/165082093-907e74b7-bb73-4020-9dd6-11ab665f695a.png)

**Comment by RaphaelRochet** [comment]
Trust me I tried.
But "kgx" is not usable. Looks like it can only be started with DBus.
If you can make this ting to work, it would be nice.

**Comment by rffontenelle** [comment]
Like this?

```
kgx -e 'sh -c "sudo pacman -Syu ; echo Done - Press enter to exit; read"'
```

**Comment by RaphaelRochet** [comment]
I tried on the gnome os image, do you think it may be different in Arch ?
