### ISSUE TITLE
[Function request] Hope to switch the GNOME terminal as the GNOME console!

### ISSUE THREAD

**Issue by gqcdm** [RaphaelRochet/arch-update#191]
Console opening command is "xdg".
Thanks!

**Comment by RaphaelRochet** [comment]
Hi, I won't change the default for now,  but you can use Console if you want by changing the command in the settings. You have examples on [the wiki](https://github.com/RaphaelRochet/arch-update/wiki) : 
```kgx -e '/bin/sh -c "sudo pacman -Syu ; echo Done - Press enter to exit; read _" '```
