### ISSUE TITLE
 Use `pkexec` instead of `sudo` in the  `UPDATE_CMD`.

### ISSUE THREAD

**Issue by nsfoxer** [RaphaelRochet/arch-update#201]
I think it is better to use `pkexec` instead of `sudo` for permission authentication.

```js
let UPDATE_CMD  = "gnome-terminal -- /bin/sh -c \"pkexec pacman -Syu ; echo Done - Press enter to exit; read _\" ";
```

![图片](https://user-images.githubusercontent.com/32675834/217714044-063983f7-44a1-4f2b-a5a2-cf86dff198a2.png)

**Comment by RaphaelRochet** [comment]
Hi, 
I don't think PolicyKit is mandatory with Arch. ? I don't want to add a dependancy.
Anyway, you are free to use pkexec if you want, and even suggest it the wiki for other users !
