### ISSUE TITLE
Gnome 44 support

### ISSUE THREAD

**Issue by gilvbp** [RaphaelRochet/arch-update#204]
Using gnome 44 I'm getting this error:

theme.set_custom_theme is not a function

**Comment by RaphaelRochet** [comment]
And we go again. New GNOME release. Chances are I'll check this when GNOME Shell 44 hits Arch extra.

**Comment by Neo-29** [comment]
Will it be ready for arch on time?

**Comment by RaphaelRochet** [comment]
No it won't. But  I will quickly  test and release a Gnome 44 compatible version as soon as Gnome 44 drops on Arch's extra repo. Expect it  like a day or two after :)

**Comment by Neo-29** [comment]
Fair enough... not a big deal

**Comment by PHLAK** [comment]
FYI, GNOME 44 is now in Arch extras.

**Comment by RaphaelRochet** [comment]
Good. Then as said, expect a release very soon.

**Comment by Neo-29** [comment]
> Good. Then as said, expect a release very soon.

Extension fully working as it is 👍😉

**Comment by RaphaelRochet** [comment]
Oh really ? No issue with gtk theming ? Coooool

**Comment by Neo-29** [comment]
nope 

![image](https://user-images.githubusercontent.com/90937180/236641359-8540bec8-0d64-453b-bd33-66c9a2d5ee1f.png)

![image](https://user-images.githubusercontent.com/90937180/236641375-ccbbfa19-9ed1-48bb-b2c7-0dbd1cd5c7c1.png)

**Comment by javmorin** [comment]
FYI, I just updated to 44 via official repo, and after tweaking allowed versions for this plugin, I get the error reported by @gilvbp `theme.set_custom_theme is not a function`.  Not sure how it's working for @Neo-29

**Comment by Neo-29** [comment]
> FYI, I just updated to 44 via official repo, and after tweaking allowed versions for this extension, I get the error reported by @gilvbp `theme.set_custom_theme is not a function`. Not sure how it's working for @Neo-29

Do you use adwaita as shell? No third party?

**Comment by Neo-29** [comment]
I suggest of not
- uninstall, reinstall.
- reset org.gnome extension settings of needed.

**Comment by RaphaelRochet** [comment]
Damned. I may need to tweak the code a bit after all.

**Comment by RaphaelRochet** [comment]
Alright. I have the issue. Working on it?

**Comment by Neo-29** [comment]
> Alright. I have the issue. Working on it.

What's the cause?
Theme?

**Comment by RaphaelRochet** [comment]
Oops, forgot to update metadat ^^"
Working nicely, tried with X11 and Wayland.

@javmorin' error may be harder to track down than I though :(

**Comment by RaphaelRochet** [comment]
@javmorin Do you have "Use builtin icons" enabled ?

**Comment by javmorin** [comment]
> Do you use adwaita as shell? No third party?
Yes, adwaita (default) for all theme settings in gnome. No third party stuff other than extensions.


> @javmorin Do you have "Use builtin icons" enabled ?
I didn't, but turning that on seems to have fixed the issue.

**Comment by RaphaelRochet** [comment]
There's a gtk3 function that was called "set_custom_theme" here, renamed "set_theme_name" in gtk4. I hate when they do this.
This bug may be there for a while ...

**Comment by javmorin** [comment]
I don't recall ever disabling that option, and the built-in icons are fine by me, so no issue on my side if a fix for custom icons isn't quick. 

FYI: I see this in the Gnome 44 extension notes: https://gjs.guide/extensions/upgrading/gnome-shell-44.html#gtk-icontheme

**Comment by RaphaelRochet** [comment]
Thanks for the point. Fun note, I was using this before but switched because it had bugs ... I will probably have to switch again.
I have submitted v52 to ego ;)

There's a little bonus : settings now use adwaita style.

**Comment by RaphaelRochet** [comment]
It's live ;)

**Comment by Neo-29** [comment]
> It's live ;)

Nice with adwaita style! 👍👍👍.
