### ISSUE TITLE
Fedora adaptation?

### ISSUE THREAD

**Issue by Neo-29** [RaphaelRochet/arch-update#206]
Hello,

I used your wiki to change the commands for fedora, it works fine except the refreshing process after the updates, which is not done automatically.

Have you or someone an idea of what can be changed in the config?

I suppose it'will be in replacement of `/var/lib/pacman/local`

**Comment by Neo-29** [comment]
Edit 

use `/var/lib/rpm` ( which can be added to wiki)makes the extension work perfectly with fedora , following the wiki for the rest.

What could be cool is creating the appropriate icons for fedora
I'm no gimp expert, but if someone coul do it , that could be great

cheers

**Comment by Neo-29** [comment]
> Edit
> 
> use `/var/lib/rpm` ( which can be added to wiki)makes the extension work perfectly with fedora , following the wiki for the rest.
> 
> What could be cool is creating the appropriate icons for fedora I'm no gimp expert, but if someone coul do it , that could be great
> 
> cheers

@RaphaelRochet

**Comment by purejava** [comment]
You can check out

[![ego](https://raw.githubusercontent.com/purejava/fedora-update/main/ego.svg)](https://extensions.gnome.org/extension/6406/fedora-linux-update-indicator/)

it’s a fork if this extension for Fedora.

**Comment by Neo-29** [comment]
I saw that.
