### ISSUE TITLE
[Feature request] Debian and apt

### ISSUE THREAD

**Issue by Miccio-AN** [RaphaelRochet/arch-update#208]
Is there a way to adapt it to a Debian or derivative distribution that uses APT?
Thanks!

**Comment by RaphaelRochet** [comment]
Hi,
Yes it should be possible, although a bit of research may be needed to adjust settings :
- command to list pending updates
- command to upgrade
- folder to monitor for changes
I'm surprised nobody added this to the wiki yet !

**Comment by Lythenas** [comment]
I'm on Ubuntu 22.04. I used the following:

- command to list packages: `/bin/sh -c "/usr/lib/update-notifier/apt-check --package-names 2>&1"`
- disable output parsing
- command to update packages: `gnome-terminal -- /bin/sh -c "set -x; sudo apt update && sudo apt upgrade ; echo Done - Press enter to exit; read _"`
- Pacman local directory: `/var/lib/dpkg/info` (although this one did not work, but looking at the code, I think the extension does not pick up the new path after changing it in the settings)

You need to install `update-notifier-common` (was already installed for me).

I can add this to the wiki, but would be good if someone validates it first. Possibly also on other debian(-based) distros.

**Comment by RaphaelRochet** [comment]
Indeed, folder monitoring change needs a restart. I shall fix this.

**Comment by Miccio-AN** [comment]
I can't find the command to list packages in Debian 12. 
Maybe can I use something like this? 

/bin/apt-get dist-upgrade | grep -o "^[[:digit:]]\+"

But: even without the "apt update" command ?

**Comment by RaphaelRochet** [comment]
Debian 12 does not have "update-notifier-common" package ?

**Comment by Miccio-AN** [comment]
Apparently not - Unfortunately that package doesn't exist in Debian

**Comment by RaphaelRochet** [comment]
Fact is, as a normal user yon can't update package list, so you need either something to check updates with no root access (under Arch this what we do) or check for updates in the background.
Maybe look into unattended-upgrades package in debian ? It is meant for automatic updates but maybe it can update without installing ? Then something like `apt list --upgradeable` might be a start point to list upgrades (however it seems not script-friendly)

**Comment by Lythenas** [comment]
After searching a bit I found this: https://unix.stackexchange.com/a/105486 You might be able to run it without sudo because of the `-s` (simulate) flag. But not sure.

**Comment by Miccio-AN** [comment]
In fact, that's exactly what I tried to do.
At the moment my system is up to date and it "seems" to work. 
As soon as I check when there are new updates I will let you know!
