### ISSUE TITLE
Rejected from extensions.gnome.org

### ISSUE THREAD

**Issue by RaphaelRochet** [RaphaelRochet/arch-update#219]
I had the Gnome 45 release rejected. Some changes are required.

> 1. You cannot create objects in global scope (line 64 extension.js).
> 
> 2. You cannot import `Gtk` into shell process (line 25 extension.js):
>     https://gjs.guide/extensions/review-guidelines/review-guidelines.html#gtk-and-gdk-imports
> 
>     Use `St.IconTheme` instead:
>     https://gjs-docs.gnome.org/st13~13-icontheme/

**Comment by RaphaelRochet** [comment]
Addressed in 303973108a5279fc6357328b83a5e1550626b283 and b8affc2d5eacf20031409b9527c29aeb36996c20 .
New release (v56) done and uploaded ... fingers crossed :crossed_fingers:

**Comment by rffontenelle** [comment]
Nice to see they spotting this bug before it hits the end-user.
