### ISSUE TITLE
Package names are underlined

### ISSUE THREAD

**Issue by horga83** [RaphaelRochet/arch-update#222]
For some reason all the package names are now underlined, IMHO it makes it more difficult to read.  The version numbers are normal.
If this is intended would it be easy to add a setting to change the names back to normal?

**Comment by RaphaelRochet** [comment]
They are now like links : you can click on a package to open the repo details page.
If you don't this feature, you can disable it by emptying "package info command" in advanced options.
( default is `xdg-open https://www.archlinux.org/packages/%2$s/%3$s/%1$s`  )

**Comment by horga83** [comment]
Thanks for the reply, it's not the feature, I don't like the underlined
text, for some reason I find it harder to read.

**Comment by RaphaelRochet** [comment]
I cannot disagree :) I think I'll add an option to disable underlining, should be easy enough.

**Comment by Jucgshu** [comment]
While you're at it, would it be possible to add an option to add more control over fonts including underlines, italic, bold and size? That would be awesome.

Anyway, thanks for your work!

**Comment by RaphaelRochet** [comment]
Done, will be in next release :)

**Comment by Jucgshu** [comment]
Awesome news, can't wait to try it out!
