### ISSUE TITLE
AUR : pamac issue

### ISSUE THREAD

**Issue by Pommede** [RaphaelRochet/arch-update#224]
when i put /usr/bin/checkupdates; pamac checkupdates -aq
it says that i need pamac-contrib to use the script 'checkupdates'
but ihave it already... :-(

i tried /usr/bin/checkupdates ; pamac checkupdates -aq and /usr/bin/checkupdates && pamac checkupdates -aq
nothing happened

sorry i'm a newbie ;-)

**Comment by RaphaelRochet** [comment]
Hi,
Did you have a look on [the wiki](https://github.com/RaphaelRochet/arch-update/wiki) ?
Looks like pamac does official repos + aur

> [pamac](https://github.com/RaphaelRochet/arch-update/wiki#pamac)
> 
>     Check command : pamac checkupdates -aq
>     Update command : gnome-terminal -- sh -c  "pamac-manager --updates"

**Comment by Pommede** [comment]
euh..that's what i did ??
and when i only put pamac checkupdates -aq, it says no such a file or directory...
on check command...update command is ok..

**Comment by RaphaelRochet** [comment]
Does `pamac checkupdates -aq` works in a terminal ?

**Comment by Pommede** [comment]
yep

**Comment by RaphaelRochet** [comment]
Ok.  Should work then. Something's wrong somewhere ;)
Plz attach screenshots of your extension setup and error messages. Maybe I'd spot something ...

**Comment by Pommede** [comment]
how do i have to write it ?
/usr/bin/checkupdates; pamac checkupdates -aq or
/usr/bin/checkupdates ; pamac checkupdates -aq or
/usr/bin/checkupdates && pamac checkupdates -aq ?

**Comment by Pommede** [comment]
![Capture d’écran du 2023-10-30 19-47-56](https://github.com/RaphaelRochet/arch-update/assets/149373181/72f980c1-ebc1-4f6f-beaf-3ce2cbe7d4fc)

sorry in french...when i wrote only pamac checkupdates -aq

**Comment by Pommede** [comment]
![Capture d’écran du 2023-10-30 19-51-34](https://github.com/RaphaelRochet/arch-update/assets/149373181/3e998e20-21ac-49c1-a0bb-31122ae2382e)

**Comment by RaphaelRochet** [comment]
Maybe try this : `/usr/bin/pamac checkupdates -aq`
( You can check in a terminal with `whereis pamac` if `/usr/bin/pamac` is right )

**Comment by RaphaelRochet** [comment]
Probably an AUR update. pamac looks for both official and aur. Pacman checks only official.

**Comment by Pommede** [comment]
it's the opposite that's why i ask ;-)
pacman 3
pamac 2

**Comment by RaphaelRochet** [comment]
Oh ... maybe a repo refresh difference. 
`pacman -Syyu` will force refresh, while `pacman -Syu` may not.
The script checkupdates will not force if run too often (calls pacman with one 'y' option).
 There may be a similar option with pamac ....

**Comment by Pommede** [comment]
i've got 3 now !
yes probably a refresh or an update from a repo...
Again thks a lot!
