### ISSUE TITLE
Check AUR updates and show them in the topbar icon

### ISSUE THREAD

**Issue by Neo-29** [RaphaelRochet/arch-update#225]
Hello Raphael,

I tried this command to try to spawn AUR updates in the icon with  `/usr/bin/checkupdates ; /usr/bin/yay -Qua` in the box command to checkupdate in advanced settings without success.

Is there a way to implement that?

Tks

![issuearchupdate](https://github.com/RaphaelRochet/arch-update/assets/90937180/2036c97a-7d78-4845-a97b-21fad8f5a286)

**Comment by RaphaelRochet** [comment]
When using a complex command line, you need to call a shell first, did you try what's in the wiki : 
```
/bin/sh -c "(/usr/bin/checkupdates; /usr/bin/yay -Qu --color never | sed 's/Get .*//') | sort -u -t' ' -k1,1"
```

**Comment by Neo-29** [comment]
> When using a complex command line, you need to call a shell first, did you try what's in the wiki :
> 
> ```
> /bin/sh -c "(/usr/bin/checkupdates; /usr/bin/yay -Qu --color never | sed 's/Get .*//') | sort -u -t' ' -k1,1"
> ```

My bad.....

All is already in the wiki I missed!

Sorry!

Closing the issue and tks for taking time to answer anyway
