### ISSUE TITLE
wiki error with the update command for yay

### ISSUE THREAD

**Issue by Aviortheking** [RaphaelRochet/arch-update#229]
When I copy the update command for yay it fail because there is no `'` at the end of the line

before:
```
kgx -e '/bin/sh -c "yay ; echo Done - Press enter to exit; read"
```

after:
```
kgx -e '/bin/sh -c "yay ; echo Done - Press enter to exit; read"'
```

I can't edit the wiki so I created an issue :D

**Comment by RaphaelRochet** [comment]
Hi, you should be able to edit the wiki !

**Comment by Aviortheking** [comment]
Awesome ! I edited it to make it work !
