### ISSUE TITLE
Enhancement archlinux news 

### ISSUE THREAD

**Issue by Neo-29** [RaphaelRochet/arch-update#233]
Hi Raphaël,

Is it possible to add a feature:
- adding archlinux news informations?

Could be cool.

Tks

**Comment by RaphaelRochet** [comment]
Hi,
Sorry, won't do.
I adhere to KISS pinciple, and this too much different from what the extension currently does.

Maybe have a look at https://github.com/slaclau/arch-update-security-news which is a fork of arch-update with news 

Or I may suggest you to subscribe to rss, newsletter or other means to get news about Arch. 
RSS feed on Thunderbird works well : for example I use https://archlinux.fr/feed/atom (french) but https://archlinux.org/feeds/news/ exists too (english)

**Comment by Neo-29** [comment]
No problem.
I saw the fork, but not confident in someone just starting with the extension fork.

I already use rss so no problem, but I just thought of it as an option in the extension settings.

But I totally get your point.
