### ISSUE TITLE
PACKAGE_INFO_CMD  ==> Bad Request

### ISSUE THREAD

**Issue by GaVenga** [RaphaelRochet/arch-update#235]
On Manjaro testing the command for updating "cmake"  (example!)
xdg-open https://www.archlinux.org/packages/%2$s/%3$s/%1$s
gives the error: 404 - Page Not Found
(Same in FireFox:)
https://archlinux.org/packages/REPO/ARCH/cmake/   ==>  404 - Page Not Found
Correct path should be:
https://archlinux.org/packages/extra/x86_64/cmake/

**Comment by RaphaelRochet** [comment]
Hi, items are parsed from the output of `pacman -Si`.
It looks for Repository and Architecture lines.

Do you have those on Manjaro ?

```
$ LANG=C pacman -Si cmake 
Repository      : extra
...
Architecture    : x86_64
...
```

**Comment by GaVenga** [comment]
LANG=C pacman -Si cmake 
gives correct output.
Manjaro Gnome uses zsh - may be this the reason?

**Comment by RaphaelRochet** [comment]
REPO and ARCH in the url are placeholders that should be replaced with real values fetched from `pacman -Si`
That's really strange, it should work from what you pasted there.

Anything in log ?
Maybe run a `journalctl -f` in a terminal and try to open a package info, see if something about it prints.

**Comment by GaVenga** [comment]
There is currently no update.
But why are this two placeholders not replaced?

**Comment by RaphaelRochet** [comment]
These are not variables, they are just initial value put in variables. Easier to spot than empty values.

Now, either the pacman call does not work, or the output fetching does not work. When you have a update and can check if something appears in log me may have more info towards one or the other ...

**Comment by GaVenga** [comment]
I asked in manjaro forum, may this help?
https://forum.manjaro.org/t/xdg-open-script-not-working/161218

**Comment by RaphaelRochet** [comment]
You are heading in the wrong direction. xdg-open is working as intended. If the extensions asks it to open "https://archlinux.org/packages/REPO/ARCH/cmake/" then that's what it's doing.. xdg-open is not responsible for REPO/ARCH replacement, it juste serves as a tool to open a url.

The issue you have is within the extension, when it comes to populate the "%2$s/%3$s/%1$s" part of the command, which is eventually  replaced by `REPO/ARCH` (the placeholders) instead of `extra/x86_64` (the values that shoudl be fetched from `pacman -Si`)

**Comment by GaVenga** [comment]
Today:


> Anything in log ?
> Maybe run a journalctl -f in a terminal and try to open a package info, see if something about it prints.
==>  journalctl -f  ==>  systemd[876]: Failed to start Application launched by gnome-shell.
The paket to update was "mkinitcpio", and the resulting URL in Firefox is: 
https://archlinux.org/packages/REPO/ARCH/mkinitcpio/
404 - Page Not Found
correct: https://archlinux.org/packages/core/any/mkinitcpio/  ==> REPO=core and ARCH=any...
BUT: the version for ARCH differ from Manjaro so that this feature is not useful for Manjaro-users
and therefore: do not use it with Manjaro.
