### ISSUE TITLE
Yay updates

### ISSUE THREAD

**Issue by bircni** [RaphaelRochet/arch-update#236]
When dependencies are installed with yay they don't show up.
Is there a possibility to add this?

**Comment by RaphaelRochet** [comment]
Hi,
I guess you already set the check command to use yay.
The extension displays whatever yay outputs. If something is missing, look into yay options maybe.

**Comment by bircni** [comment]
@RaphaelRochet nope i didnt, where can i do this?

**Comment by RaphaelRochet** [comment]
You can edit these in settings.
The wiki can give you examples of what to use for yay.
https://github.com/RaphaelRochet/arch-update/wiki#yay

**Comment by GaVenga** [comment]
Using Manjaro I do:
Checking for updates:
/usr/bin/pamac checkupdates -aq
Update:
gnome-terminal -- /bin/sh -c "yay -Syyu ; echo Done - Press enter to exit; read _"
