### ISSUE TITLE
Show when last check was performed

### ISSUE THREAD

**Issue by sabr-math** [RaphaelRochet/arch-update#238]
In addition to showing `Up to date :)` could you also indicate when the last check command was performed?

I have in mind something like `last checked 10 minutes ago` or `last checked 3 hours ago`,
but haven't thought too much about how to design this feature.

Also a big thank you for your work on this extension.

**Comment by RaphaelRochet** [comment]
Why not. Doesn't seem too complicated to implement ;)
Although I think I'd prefer an absolute date/time rather than relative :thinking:
