### ISSUE TITLE
Margin/padding in update list - version 61

### ISSUE THREAD

**Issue by drakkar1969** [RaphaelRochet/arch-update#239]
With the update to version 61, the margins/padding in the update list seem to be off (no margin left/top/botton):

![screenshot](https://github.com/user-attachments/assets/279acafe-b965-40fe-ab14-b79f23054ba7)

Thanks for the extension, couldn't do without it!

**Comment by RaphaelRochet** [comment]
Some tweaks done ;)

**Comment by drakkar1969** [comment]
Thank you
