### ISSUE TITLE
Not working in Gnome 47

### ISSUE THREAD

**Issue by realquink** [RaphaelRochet/arch-update#247]
Hello,

Thanks for your work on this!

I just updated my system about a week or so ago and since then this indicator no longer works. My Gnome version is 47:

![image](https://github.com/user-attachments/assets/91b04524-ac21-46a1-85e9-33efd6efec32)

**Comment by RaphaelRochet** [comment]
Hi, sorry this is not my extension you are reffering to.
Here is **arch-update**, not **pamac-updates** ;)

**Comment by realquink** [comment]
Oh may bad, thanks for the reply!
