### ISSUE TITLE
Plural form

### ISSUE THREAD

**Issue by prescott66** [RaphaelRochet/arch-update#30]
Please create plural form for this string:

#: extension.js:217 extension.js:232
msgid "updates pending"
msgstr ""

**Comment by RaphaelRochet** [comment]
Done in 42c01aa98d58a31d065ae5da7d1020a067198a43

**Comment by RaphaelRochet** [comment]
For all other translators (@frnogueira @sorin-mihai @artur9010 @trazalca @Ralgo @kbabioch @svetlemodry ) with plural form introduction a few strings are now fuzzy in translations. It would be great if you could update them :)

I am planning a release in a few days. Thanks !

Thanks

**Comment by frnogueira** [comment]
Yes, sir! :)

**Comment by frnogueira** [comment]
pt_BR.. Done!
