### ISSUE TITLE
Use alternative terminal

### ISSUE THREAD

**Issue by TasosKan** [RaphaelRochet/arch-update#36]
I changed gnome-terminal from the default update command, to terminix. Now whenever I want to update, terminix will not show up. I am sure that the command to open it is correct. Is there a way to use a different terminal client than the default?

**Comment by RaphaelRochet** [comment]
You can use whatever terminal you want. The tricky part is the quote escaping part.

Are you sure terminix supports command line argument ?

The default command line is :
```gnome-terminal -e 'sh -c  \"sudo pacman -Syu ; echo Done - Press enter to exit; read\" '```

**Comment by frnogueira** [comment]
Don't work! The function -e is unknown in terminix.
Open the terminal, and run:
terminix -e 'sh -c \"sudo pacman -Syu ; echo Done - Press enter to exit; read\" '
I use terminix too... ;)

**Comment by frnogueira** [comment]
Ps.: I try -x and -a and don't work too... :(
I will open a issue in the terminix project.

**Comment by frnogueira** [comment]
It's work!

When I run like this:

terminix -x 'sh -c "sudo pacman -Syu ; echo Done - Press enter to exit; read" '

Now, works! ;) Raphael... I cut the " \ " ...

**Comment by TasosKan** [comment]
I can confirm your command is working. Thank you @frnogueira. Issue is resolved.
