### ISSUE TITLE
disable dropdown to see updates

### ISSUE THREAD

**Issue by pank** [RaphaelRochet/arch-update#44]
Hi,

Thanks for providing this extension.

It would be nice if the extensions would just show all available updates rather than hiding them behind an extra menu layer.  If there are only few updates (this could be a configurable number) it would be nice to have these updates shown immediately.

Thanks,
Rasmus

**Comment by RaphaelRochet** [comment]
I think about this too. This feature should be added soon.

**Comment by RaphaelRochet** [comment]
And ... done in 631cf2679b56bcfb1886bcfbe423eca42731279c !

**Comment by pank** [comment]
Thanks a bunch!

**Comment by RaphaelRochet** [comment]
You can try it by downloading the git version. I will wait a few days before releasing to ego. (Both for testing and giving time to translators)
