### ISSUE TITLE
Showing updates with yaourt not working as expected

### ISSUE THREAD

**Issue by skogsmaskin** [RaphaelRochet/arch-update#45]
Hi! First, thank you for this tool.

I am trying to show updates from the main repo and AUR through yaourt with the command specified in the wiki:

``/usr/bin/yaourt -Qqu -a``

However no notification is made even if there are new packages available.

If I do ``yaourt -Suy --aur`` first and then cancel it - it will show the notifications on next check just fine.

Am I missing something here or is it a bug?

**Comment by RaphaelRochet** [comment]
The command is right; if you replace ```/usr/bin/checkupdates``` by ```/usr/bin/yaourt -Qqu -a``` you should have both AUR and regular repos updates.

Does ```/usr/bin/yaourt -Qqu -a``` shows updates in a terminal ?

**Comment by skogsmaskin** [comment]
Today it worked and notified me about a community-package. Not sure why it did not yesterday. Maybe bacause the widget was restarted through a reboot after I changed the settings?

Seems to work now though. Closing this ticket. Thank you for your kind reply.

**Comment by skogsmaskin** [comment]
Hmm..Closed it too early. I notified me about a community package this morning and I thought it was allright. But not about the regular packages (non-AUR) that came this afternoon.

In order to make it check for both regular packages and AUR-packages I had to do it with this command:

``/bin/sh -c "/usr/bin/checkupdates &> /dev/null && /usr/bin/yaourt -Qu -a"``

It updates and syncs the package list with checkupdates first (which uses fakeroot). Then it lists those packages + any packages in the AUR with yaourt afterwards.

**Comment by RaphaelRochet** [comment]
You're right, yaourt works like pacaur, and shows only AUR updates with ```-a``` flag. Sorry I've should have check that before. (I did not test AUR support myself)
But your command does not list non-AUR packages. You should not ignore checkupdates output, instead chain both scripts :
```/bin/sh -c "/usr/bin/checkupdates ; /usr/bin/yaourt -Qqu -a" ``` 
If this works I will update the wiki.

**Comment by skogsmaskin** [comment]
Yaourt also show regular packages (after the sync). That is why I had to silence checkupdates - otherwise I would get double.

**Comment by RaphaelRochet** [comment]
Sounds strange. Checkupdates does not store anything after it's run.
Yaourt shows regular updates only if system databases are updated (with -Syu flag)

If you continue to ignore checkupdates output, you will not see new updates until you run ```yaourt -Syu```.

**Comment by skogsmaskin** [comment]
checkupdates does two things:
```
fakeroot -- pacman -Sy --dbpath "$CHECKUPDATES_DB" --logfile /dev/null &> /dev/$
pacman -Qu --dbpath "$CHECKUPDATES_DB" 2> /dev/null | grep -v '\[.*\]'
```

**Comment by RaphaelRochet** [comment]
Yes. But the db in $CHECKUPDATES_DB is not read by subsequent yaourt calls.

**Comment by skogsmaskin** [comment]
I have added your command to test. We have to wait and see. :watch:

**Comment by skogsmaskin** [comment]
I can confirm that your suggested command is the right one. The reason I got it double was because I did ``yaourt -Suy --aur`` in between.

**Comment by RaphaelRochet** [comment]
Ok thanks for the feedback. I'll update the wiki.

**Comment by skogsmaskin** [comment]
Closing this then :)
