### ISSUE TITLE
Option to cancel update checking

### ISSUE THREAD

**Issue by DoctorJellyface** [RaphaelRochet/arch-update#49]
I tiny circle cancel button beside the "Checking for updates" would be really useful, especially when I'm e.g. on the train with a wifi that barely exists and every megabyte is precious, which is quite often for me.

**Comment by RaphaelRochet** [comment]
Hi, given your example, wouldn't an on/off switch in the menu be more useful ?
As a "cancel" action, I'll only be able to kill the check process. Maybe I can also kill any check in progress when the switch is turned off.

**Comment by DoctorJellyface** [comment]
> Hi, given your example, wouldn't an on/off switch in the menu be more useful?

No, not really, I would forget about that quickly. Besides I don't spend prolonged sessions with bad internet access. A process kill would be enough.

**Comment by RaphaelRochet** [comment]
Okay. Thanks for your feedback.
I will add this feature soon.

**Comment by DoctorJellyface** [comment]
Looking forward to it!

**Comment by RaphaelRochet** [comment]
Done in 72138c508439abaa9f4d0a0b73588edf04819322 !
I will test it for a few days to be sure there's no obvious bug and then release it.

**Comment by RaphaelRochet** [comment]
At last, it's released !
