### ISSUE TITLE
Does not support shell version

### ISSUE THREAD

**Issue by Hugao** [RaphaelRochet/arch-update#50]
Hello,
I'm using the last version of Gnome and the Tweak Tool says that the extencion doesn't support the shell version. I installed from AUR

Versions according to pacman

- gnome-shelll: 3.20.1-1
- gnome-shell-extension-arch-update: 11-1

**Comment by RaphaelRochet** [comment]
AUR is not up to date. Last version is 15, Gnome 3.20 is supported since version 14.
I will try to warn the AUR package author.

In the meanwhile, I suggest you remove the AUR package and install from extensions.gnome. org which is always up to date.

**Comment by Hugao** [comment]
@RaphaelRochet thanks
