### ISSUE TITLE
Indicator still showing updates even there are no available

### ISSUE THREAD

**Issue by marceel** [RaphaelRochet/arch-update#51]
Hello,

I have problem with the indicator addon still showing that I need to update my system.[Screenshot](http://imgur.com/ZbwlSYM).
 I tried to reinstall by deleting the directory for the addon and instaling again. Which did not help.
This is what I get when I run the checkupdates  command. This is the settings [screenshot](http://imgur.com/d4PlVQu).
[user ~]$ /usr/bin/checkupdates
ca-certificates 20150402-1 -> 20160507-1
ca-certificates-cacert 20140824-2 -> 20140824-3
ca-certificates-mozilla 3.23-3 -> 3.23-4
ca-certificates-utils 20150402-1 -> 20160507-1
dosfstools 3.0.28-1 -> 4.0-2
glib2 2.48.0-2 -> 2.48.1-1
glibc 2.23-2 -> 2.23-4
gnupg 2.1.12-1 -> 2.1.12-2
gssproxy 0.4.1-1 -> 0.5.0-3
libksba 1.3.3-1 -> 1.3.4-1
libseccomp 2.2.3-1 -> 2.3.1-1
linux45 4.5.3-1 -> 4.5.4-1
linux45-headers 4.5.3-1 -> 4.5.4-1
man-pages 4.05-1 -> 4.06-1
manjaro-release 15.12-1 -> 16.06rc1-1
nss 3.23-3 -> 3.23-4
perl 5.22.1-2 -> 5.22.2-1
xfsprogs 4.3.0-1 -> 4.5.0-1

What could be wrong? What did I changed that made the applet think that I still need to update these  programs?

**Comment by RaphaelRochet** [comment]
Seems your pacman does not detect that databases are out of sync.

Try to run ``pacman -Syyu`` from a root terminal to force database sync.

**Comment by marceel** [comment]
Hi,

Thanks, it fixed the issue. I wouldn't think that database is not synced.
