### ISSUE TITLE
Is there a way also check for AUR package update?

### ISSUE THREAD

**Issue by zoutiyx** [RaphaelRochet/arch-update#53]
I know that AUR packages can be updated with `yaourt -Syua`, but the `checkupdates` script does not query aur packages. I have modified the command which updates packages to `gnome-terminal -e 'sh -c  "yaourt -Syyua; echo Done - Press enter to exit; read" '`which does both main and AUR. Is there a way add the capability to query AUR package updates?

**Comment by RaphaelRochet** [comment]
Yes, you can customize 2 commands in settings : one for checking for updates, and one for applying updates. See [the wiki page](https://github.com/RaphaelRochet/arch-update/wiki) for examples.
Be sure to use the latest version from extensions.gnome.org ! The AUR package is out of date.

**Comment by zoutiyx** [comment]
@RaphaelRochet,

Thank you so much. I wasn't aware of the wiki section.
