### ISSUE TITLE
Add option to notify about security updates only

### ISSUE THREAD

**Issue by pulb** [RaphaelRochet/arch-update#58]
Arch is updated very frequently so there's hardly a day you won't get update notifications. IMHO it's more important to get notifications when its _really really really recommeded_ to update your system -- i.e. if security relevant updates are available.

So I propose to add a "Security updates only" option that can be implemented like this: 
- Download _<latst-month>.gz_  and _<this-month>_.gz from https://lists.archlinux.org/pipermail/arch-security/
- Unpack these files (either in-memory or into /tmp), parse all occurences of
  `pacman -Syu "packagename>=packageversion"` and create a map<packagename, packageversion>
- Run checkupdates as usual but only notify about packages that are present in the map and installed_version  < packageversion 

I'd bet there are quite a few users that would love to see this happen :)

**Comment by RaphaelRochet** [comment]
Hi, that's good ideas, but I think this would better fit in a separate script than in an gnome extensions.
A script designed to be used as a replacement for checkupdates ?

**Comment by pulb** [comment]
I don't mind if it's implemented in a script as long as it's used by your extension to notify me ;)

**Comment by RaphaelRochet** [comment]
Just to be sure I understood : you would like to see all updates but only have notifications for security issues ? 
Question : ff you only feel concerned about security updates, why not subscribing to arch-security and disable notifications ? I mean, arch-security mails give details about what's wrong, and sometimes workarounds are given. Isn't that better than a simple notification ?

**Comment by pulb** [comment]
I'm unsure about the indicator menu. Maybe it should just show all updates, maybe it should show two sections (updates and security updates). At least the notification should only show security updates if the proposed option is enabled.

The problem with subscribing to the mailing list is that it is pretty time-consuming: You have to skim through all the packages you don't even have installed to find the ones that are relevant for you. Then there are packages you're not sure about, so you have to launch pacman to check if you have it installed. 

An extension that notifies about relevant packages only would be very convenient.

Am 21. September 2016 23:51:02 MESZ, schrieb "Raphaël Rochet" <notifications@github.com>:

**Comment by pulb** [comment]
I'm gonna implement this script this evening.

**Comment by pulb** [comment]
I added the script. All you need to do is to pump its output into a Map and compare package names and versions you obtained from checkupdate.
