### ISSUE TITLE
Not working on Gnome 3.22.1

### ISSUE THREAD

**Issue by jlafrankie76** [RaphaelRochet/arch-update#60]
The latest version isnt compatable with the latest version of gnome. Please fix! This is an awesome extension.

**Comment by RaphaelRochet** [comment]
Hi, it runs perfect on Arch with gnome 3.22.1. 
Which distro do use ? Does it work if you change "3.20" to "3.22" in metadata.json ?
( you can find it in ~/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet )

**Comment by WoefulDerelict** [comment]
I happen to maintain the package for this extension out in the AUR and version 17 is working just fine on my Arch Linux system with gnome-shell 3.22.1+2+g5a08886-1

**Comment by jlafrankie76** [comment]
Not sure then. Even if I search for the extension on the extensions website it shows the updater as greyed out. (showing that its not compatible with my version). If I click install anyway it installs but doesnt show in the top left hand corner. Nor does it show in the list of installed extensions. Here is a screenshot: https://sugoi.vidyagam.es/qt/cDHUaPM.png

**Comment by RaphaelRochet** [comment]
Ok, maybe the metadata blocks ego .

I will submit a new version in no time, there's a few changes for a new release anyway ;)

**Comment by jlafrankie76** [comment]
you da man

**Comment by jlafrankie76** [comment]
also: if i force install i dont get a folder in: ~/.local/share/gnome-shell/extensions/

**Comment by RaphaelRochet** [comment]
Ok. v18 released ! It's already submitted to extensions.gnome.org. Let's hope they review it soon.

You can download the Zip file here : https://github.com/RaphaelRochet/arch-update/releases/tag/v18
Simply unzip it in ``~/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet`` (create the folder if needed)

**Comment by jlafrankie76** [comment]
Thanks, works great.
