### ISSUE TITLE
Remember last automatic check date

### ISSUE THREAD

**Issue by franglais125** [RaphaelRochet/arch-update#67]
At the moment, if a user sets the automatic check interval to something like "24 hours", and the session only lasts a few hours, the check will never take place, as it restarts with the session.
If the last check date is stored, then it can be used to set the interval for the automatic check.

In case you'd like to implement it, I implemented this for the apt-based extension here: https://github.com/franglais125/apt-update-indicator/commit/c3b7ce600cf4f80d384d720bde235792442c791e . A PR won't work, but from there it is pretty easy to see how it was done. If you have suggestions on how to improve it, I'd definitely be interested!

Cheers!

**Comment by RaphaelRochet** [comment]
I'd say it's a minor issue, as a test is done automatically at session start. But heh why not, I'll check this.

**Comment by RaphaelRochet** [comment]
Having thought about this, I won't do. As I wrote, a check is done at login so if your session lasts less than the interval, you will still always have a check done.
