### ISSUE TITLE
Implement Proxy support

### ISSUE THREAD

**Issue by josephgbr** [RaphaelRochet/arch-update#69]
Currently, the extension won't work behind a proxy, even if it is configured in Network settings of GNOME. How about implement proxy support, in order to allow verify&update anywhere?

**Comment by RaphaelRochet** [comment]
The extension itself does not check for updates. It runs another script, (checkupdates by default).
Look around on how to make checkupdates (part of pacman) work with a proxy.

**Comment by josephgbr** [comment]
One workaround is to change the command lines of checkupdates and pacman (1st and 2nd strings in advanced tab), prefixing a proxy script based on [Proxy settings](https://wiki.archlinux.org/index.php/proxy_settings) wiki page.

Will this customization be lost if you update the extension?

**Comment by RaphaelRochet** [comment]
No it won't.

**Comment by josephgbr** [comment]
Awesome!  I prefixed the commands with a proxy script (defined as a function in bashrc) that will only set the required variables (to enable proxy) if notebook is inside my "proxied" network; otherwise, it will leave them disabled. Now the extension works perfectly in my environment. Thanks!
