### ISSUE TITLE
Fuzzy Spanish PO

### ISSUE THREAD

**Issue by AlonsoLP** [RaphaelRochet/arch-update#70]
Hi.

In Spanish translation, there are some fuzzy lines that needs fix. I attached the fixed PO.
[es.zip](https://github.com/RaphaelRochet/arch-update/files/816963/es.zip)

Best regards.

**Comment by RaphaelRochet** [comment]
Thanks. It would be easier for me if you create a pull request for this. Is this possible for you ?

**Comment by AlonsoLP** [comment]
Sure. Pull request done.

**Comment by RaphaelRochet** [comment]
Thanks. I'll release it now.
