### ISSUE TITLE
Gnome Shell freezes when checking for updates while offline

### ISSUE THREAD

**Issue by CubeTheThird** [RaphaelRochet/arch-update#73]
If the extension checks for updates, and there is no internet connection, Gnome Shell will temporarily become unresponsive until the check update command terminates, which may take several minutes.
While using X.Org, keyboard and mouse input function, but the desktop does not. With Wayland, mouse and keyboard are equally frozen.

I do not know whether this is an issue with the extension, or Gnome Shell. Should it be the latter, would it be possible to implement some sort of internet connection check before running the check updates command?

**Comment by RaphaelRochet** [comment]
Hi,

This was an issue in an old version, back in 2015.

Do you use the last version ? What distro are you using ?

**Comment by CubeTheThird** [comment]
I am using regular Arch Linux. The version listed in the settings menu is "Arch-update 20", which is (as far as I can tell) the latest version released as per the shell extensions website.

**Comment by RaphaelRochet** [comment]
Ok. I'll see if I can reproduce this.

**Comment by CubeTheThird** [comment]
Hmm after recent updates, the issue no longer appears to be present. I'll do further testing just to make sure.

**Comment by RaphaelRochet** [comment]
Ok. On my side it did not happened, even once, on Arch linux.
