### ISSUE TITLE
Arch Audit support: Alert for security updates

### ISSUE THREAD

**Issue by nogweii** [RaphaelRochet/arch-update#77]
If [arch-audit](https://github.com/ilpianista/arch-audit) is installed, the extension should extra-highlight any packages that need to be updated for security alerts.

**Comment by Strykar** [comment]
This would be a welcome addition.

**Comment by slaclau** [comment]
I've made a start at adding this functionality in #223 - more work is needed still and suggestions would be appreciated

**Comment by slaclau** [comment]
For anyone still interested in this functionality, please see my fork at https://github.com/slaclau/arch-update

I will release it on GNOME extensions at some point soon.
