### ISSUE TITLE
Add option to open specific pacman wrapper for install or remove package ( like pamac or other GUI interface )

### ISSUE THREAD

**Issue by Ste74** [RaphaelRochet/arch-update#83]
Hi there, we have forked your extension to ship with our Manjaro Gnome edition ( we have changed icon status and command to open pamac when update is ready ) .  We like your extension because offer a native integration with gnome-shell ;) .
Is possible add an option to open a packager manager ( in our case pamac ). 
https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#Graphical_front-ends

Regards
Stefano

**Comment by RaphaelRochet** [comment]
How should I do when (and this is the default on ArchLinux) there is no package manager at all ?

**Comment by Ste74** [comment]
At the moment we have hard coded pamac in your app : 
https://github.com/Ste74/arch-update/blob/master/extension.js#L59
and change the command for checking updates and apply the updates : 
https://github.com/Ste74/arch-update/blob/master/extension.js#L53
with our scripts and this is ok because someone can adds a custom commands
I don't know too of js coding but is possible add in settings a switch ( on/off ) if is on do the possibility to open a packager manager and add a option in main window.. only a tought

**Comment by RaphaelRochet** [comment]
Ok. I guess I'll simply add a optional package manager command, that'll show only if defined.

**Comment by RaphaelRochet** [comment]
Please try 800c156 ;)
