### ISSUE TITLE
Extension doesn't ignore packages specified in the /etc/pacman.conf

### ISSUE THREAD

**Issue by snqlby** [RaphaelRochet/arch-update#87]
There is an option in the file that is needed to ignore the packages during the update (IgnorePkg). My suggestion is to add a feature for the extension to ignore such packages in the list.

**Comment by RaphaelRochet** [comment]
The extension is not doing the update check itself, it's (by default) checkupdates.
If you want to change its behavior, you can edit the command line if the extension prefs.

This said, I have a packet in IgnorePkg and it does not show up in the extension.

**Comment by snqlby** [comment]
> This said, I have a package in IgnorePkg and it does not show up in the extension.

I agree with you. It works great for checkupdates utility, but there are pacaur and yaourt utilities.
The following examples:
`/bin/sh -c "/usr/bin/checkupdates ; /usr/bin/yaourt -Qqu -a`
`/bin/sh -c "/usr/bin/checkupdates && /usr/bin/pacaur -Qqu -a"`
ignores IgnorePkg option and displays packages from the AUR and locally installed sources (taken from the arch archive for downgrade for example) in the extension. Pacaur and yaourt don't update the AUR packages from the IgnorePkg but displays them with `pacaur/yaourt -Qqu -a`.
As a result, the extension works incorrectly. The extension writes that there is an update, but in fact it does not exist, because the pacaur or yaourt utilities will ignore these packages during the upgrade process.
Now I'm using my custom bash wrapper for checkupdates which reads the file with IgnorePkg and deletes the packages, if they exist

My suggestion is to read the pacaur.conf file and filter it additionally at the arch update extension level.

**Comment by RaphaelRochet** [comment]
You can add command line options to yaourt to make it read pacman.conf or
other conf, and so it will honor your settings.
I dunno for pacaur, but clearly I don't think it is up to the extension to
filter this.
