### ISSUE TITLE
Up-to-date message replaces applications caption.

### ISSUE THREAD

**Issue by conqp** [RaphaelRochet/arch-update#91]
I just noticed, that the update indicator's message for up-to-dateness replaced the "Applications" caption of the respective menu (see attachments).

![bildschirmfoto von 2018-01-03 12-07-26](https://user-images.githubusercontent.com/3766192/34518268-f945d0b0-f07e-11e7-806c-4dd5ee4f9526.png)
![bildschirmfoto von 2018-01-03 12-07-36](https://user-images.githubusercontent.com/3766192/34518269-f99d94da-f07e-11e7-8699-eb7029e1b68a.png)

**Update:**
Now this override happens also if updates are available.
It seems, that the caption is just being overridden every time.
![bildschirmfoto von 2018-01-03 19-04-00](https://user-images.githubusercontent.com/3766192/34533107-040aa266-f0b9-11e7-87fd-dd8783857425.png)

 **Update II:**
After two days I cannot reproduce this problem any more.

**Comment by RaphaelRochet** [comment]
Oh, ok. Thanks for your updates. I could not reproduce this either. Feel free to reopen the issue if it comes again !
