### ISSUE TITLE
Too many arguments to method Gio.File.monitor

### ISSUE THREAD

**Issue by mblob** [RaphaelRochet/arch-update#92]
Hi,

Dunno if it is important or not just reporting ...

> Jan 10 11:41:12 xxxx gnome-shell[16558]: JS WARNING: [/home/xxxx/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js 242]: Too many arguments to method Gio.File.monitor_directory: expected 2, got 3

Thanks for tht usefull app.
  [Gnome versions](https://gist.github.com/mblob/16de10b1f2171e0da74f70a5a6a2858c)

**Comment by RaphaelRochet** [comment]
Thanks. I think it has been fixed by 99d10e36e72c557ce204fc0d5aabb23eb3bf0141. It should be fixed in next release, which is currently blocked by issue #81
