### ISSUE TITLE
"Too many arguments to method Gio.File.monitor_directory: expected 2, got 3"

### ISSUE THREAD

**Issue by rffontenelle** [RaphaelRochet/arch-update#94]
Not sure if this is really a problem, but I found some of this message in `journalctl`:

> jan 26 08:49:57 HOSTNAME gnome-shell[2026]: JS WARNING: [HOME/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js 242]: Too many arguments to method Gio.File.monitor_directory: expected 2, got 3

System: Arch Linux 64-bit, everything up-to-date.

**Comment by RaphaelRochet** [comment]
This is fixed in last release, that is currently waiting review :)

Le ven. 26 janv. 2018 12:33, Rafael Fontenelle <notifications@github.com> a
écrit :
