### ISSUE TITLE
"Update now" opens pamac-manager instead of pamac-updater

### ISSUE THREAD

**Issue by kq01526** [RaphaelRochet/arch-update#97]
Hi @RaphaelRochet ,

in https://github.com/RaphaelRochet/arch-update/issues/83 @Ste74 asked you to add an option to open a GUI package manager.

I've set:

> Command to open package manager (optional):
> `/usr/bin/pamac-manager`

It's working fine, thanks.

I've also set:

> Command to update packages:
> `/usr/bin/pamac-updater`

But that doesn't work. Once you click on "Update now", it opens `pamac-manager` instead of `pamac-updater`.

Any idea what could be causing this and how it could be fixed?

When launching `pamac-updater` from a terminal or via ALT+F2, it properly launches `pamac-updater`.

Removing:

> Command to open package manager (optional)
> `/usr/bin/pamac-manager`

does not help.

Regards

**Comment by Ste74** [comment]
`pamac-updater` and `pamac-manager` is integrated in `pamac-manager` .. this is the reason because we use `update-notifier` script to check updates but for install we use `pamac-manager`

**Comment by kq01526** [comment]
@Ste74 I just found the solution:

You need to change

> Command to update packages:
> `/usr/bin/pamac-updater`

to:

> Command to update packages:
> `pamac-updater`

Then it works fine :slightly_smiling_face: .

So you just need to leave out the `/usr/bin/` part :slightly_smiling_face: .

Closing this one :slightly_smiling_face: .
