### ISSUE TITLE
Script call "check now"

### ISSUE THREAD

**Issue by alexheretic** [RaphaelRochet/arch-update#99]
Thank you for this extension! I'd like to be able to invoke **"Check now"** functionality via a script so I can call it after a local repository has been updated.

Is there any way to do this?

**Comment by RaphaelRochet** [comment]
You can touch the pacman directory (default is /var/lib/pacman/local). The extension will update a few seconds later.

**Comment by alexheretic** [comment]
Yep that should work, thanks. Is there any current non-root way?

**Comment by RaphaelRochet** [comment]
A relative safe way may be to touch a world-writable file inside the directory.

**Comment by alexheretic** [comment]
Yes I think that'll work a treat. Thanks again!
